version: "3.1"
services:
  web:
    image: iweinert/drupal
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.3"
      restart_policy: 
        condition: on-failure
    secrets:
      - source: "mysqlpwd"
        target: "mysqlpwd"
    ports:
      - "80:80"
secrets:
  mysqlpwd: 
    external:
      name: "mysqlpwd"