version: "3"
services:
  web:
    image: iweinert/drupal
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.3"
      restart_policy: 
        condition: on-failure
    ports:
      - "80:80"